# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  frontend-build-test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci --force

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Run linter
          command: npm run lint

      - run:
          name: Run unit tests
          command: npm run test

      - run:
          name: Run tests coverage
          command: npm run coverage

      - run:
          name: Install Xvfb - Cypress required dependency
          command: |
            npm run install:xvfb

      - run:
          name: Run Cypress Tests
          command: |
            npm run cy:run-unit

      - run:
          name: Create Istanbul coverage badges
          command: |
            npm run make-badges:ci
    - cypress/run:
        start-command: 'npm run start'
        cypress-command: 'npx cypress run --parallel --record  --key e398a217-53a3-4229-8859-aedab251f257 --group all tests'
        parallelism: 5
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  frontend-build-test-workflow:
    jobs:
      - frontend-build-test